### PR TITLE
feat: Set preferred MFA provider

### PR DESCRIPTION
**Pull request by zagraves**
In one of my Okta accounts, I have multiple MFA providers (google, okta verify). I want to be able to specify which one I'd prefer to use when running the tool to make it easier to use. For example, using my "google" one-time password in 1password, instead of opening Okta Verify on my phone.

```
> aws_okta_keyman -o organization -a exampleAppIDFromOkta/234 -u username@example.com -P google

22:54:00   (INFO) AWS Okta Keyman v0.4.0
Password:
22:54:13   (WARNING) MFA Requirement Detected - Enter your GOOGLE code here
MFA Passcode: 111111
22:54:20   (INFO) Successfully authed [...]
22:54:20   (INFO) Getting SAML Assertion from [...]
22:54:21   (INFO) Assuming role: [...]
22:54:22   (INFO) Wrote profile "default" to /Users/[...]/.aws/credentials
22:54:22   (INFO) Current time is 2018-08-30 05:54:22.159636
22:54:22   (INFO) Session expires at 2018-08-30 06:54:22+00:00
```

Open to feedback on how to fix the single code style error. Not sure your preferred format for constructor args.

```
aws_okta_keyman/okta.py:90:80: E501 line too long (91 > 79 characters)
```

### CODE REVIEW

**Comment by zagraves** [comment]
Ping

**Comment by nathan-v** [comment]
Hi @zagraves! Thanks for adding this. I'll take a look (and fix the test automation) soon.

**Comment by nathan-v** [comment]
@zagraves If you can rebase and push the tests should all pass now and once that's done we can get this in and get the new version published.

Thanks!

**Comment by nathan-v** [comment]
Opened #55 to cover this. This PR is stale at this point and would require a bit of work to merge. Closing in favor of a replacement.

**Pull request closed without merging**
