### PR TITLE
feat: Add region argument

### PR DESCRIPTION
**Pull request by zagraves**
I've added an optional argument to specify a region that is passed along to Session and written to the credentials file. Appreciate any feedback/changes to get this in. Thank you for an awesome tool.

### CODE REVIEW

**Comment by nathan-v** [comment]
Hi @zagraves ! Thanks for this! I apologize for the very long delay in my response. I've been pulled off to another project at work lately and have been busy with that but I'll be back focused on this one soon(ish).

At first look the PR looks good; I need to fix the code coverage automation that's broken that is the cause of these being marked failed. Once I have some time to sort that out I'll re-run these and see about getting this merged.

Thank you!

**Comment by zagraves** [comment]
@nathan-v Thanks!

**Comment by zagraves** [comment]
Ping. Would love to get these changes in. Let me know how I can help

**Comment by aosyborg** [comment]
Just adding another voice here: I would love to see these changes in as well. Thanks.

**Comment by smithtim** [comment]
I would also like to see these changes included.

**Comment by nathan-v** [comment]
@zagraves If you can rebase and push the tests should all pass now and once that's done we can get this in and get the new version published.

Thanks!

**Comment by smithtim** [comment]
Any updates on this?

**Comment by nathan-v** [comment]
Merged in #35 

Closing.

**Pull request closed without merging**
